---
author: "Onval GmbH"
title-block-banner: "#27445C"
params:
  save_data_file: ""
execute:
  echo: false 
  warning: false
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
css: styles.css
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(sf)
library(knitr)
library(tmap)

options(knitr.kable.NA = '')
```

# Vergleichspreise

```{r, save_data_init}
daten_all <- readRDS(params$save_data_file)
```

```{r, data_converter}
## Verwende dies, falls Datensatz übergeben wird (und nicht Pfad zum Laden der Daten)

# daten_all <- params$daten %>%
#   as_tibble() %>%
#   dplyr::mutate(Kaufdatum = as.POSIXct(Kaufdatum, origin="1970-01-01") %>% as.Date() %>% ymd())
# 
# coords <- daten_all %>% dplyr::select(geometry) %>% pull()
# colnames(coords) <- c("xco", "yco")
# 
# daten_all <- coords %>% as_tibble() %>% dplyr::bind_cols(daten_all) %>% st_as_sf(coords = c("xco", "yco"))
``` 

```{r}
load("../data/zsp_2017.Rdata")
```

```{r} 
daten_all %>%  
  st_drop_geometry() %>%  
  dplyr::select(Id = BewertungId, Kaufpreis, Kaufdatum, KaufpreisQM, Zins = zins, PreisValorisiert, 
                Bezugszeitraum = zeit_diff_jahre, Strasse, Hausnummer, Grundflaeche, NutzflaecheBerechnet, 
                Objektart, Tagebuchzahl, EintrageJahr) %>%  
   kable() 
``` 

```{r} 
tmap_mode("view")
daten_all %>% 
  dplyr::select(Id = BewertungId, Kaufpreis, Kaufdatum, KaufpreisQM, Zins = zins, PreisValorisiert, 
                Bezugszeitraum = zeit_diff_jahre, Strasse, Hausnummer, Grundflaeche, NutzflaecheBerechnet, 
                Objektart, Tagebuchzahl, EintrageJahr) %>%   
  tm_shape() +
  tm_dots(col = "red")
```
